import type { CatalogForm, Materia, Respostas } from '../../../lib/survey-types'
import { Actions } from '../ui/Actions'
import { Button } from '../ui/Button'

interface Props { form: CatalogForm; materia?: Materia; respostas: Respostas; onChange: (value: Respostas) => void; onBack: () => void; onNext: () => void; isSubmitting: boolean; isLast: boolean }
export function QuestionnaireStep({ form, materia, respostas, onChange, onBack, onNext, isSubmitting, isLast }: Props) {
  const complete = form.questions.every((question) => Boolean(respostas.opcoes[question.id]))
  return <section className="survey-enter w-full max-w-2xl px-4"><div className="mb-6 text-center"><h2 className="text-3xl font-black text-slate-950">{form.name}</h2>{materia ? <p className="mt-2 text-slate-600">{materia.nome} — {materia.docente}</p> : null}</div><div className="grid gap-6 rounded-lg border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/10">{form.questions.map((question) => <fieldset className="grid gap-3" key={question.id}><legend className="font-bold text-slate-800">{question.texto}</legend><div className="grid gap-2">{question.options.map((option) => <button className={`rounded-lg border px-4 py-3 text-left text-sm font-semibold ${respostas.opcoes[question.id] === option.code ? 'border-blue-700 bg-blue-50 text-blue-800' : 'border-slate-200'}`} type="button" key={option.code} aria-pressed={respostas.opcoes[question.id] === option.code} onClick={() => onChange({ ...respostas, opcoes: { ...respostas.opcoes, [question.id]: option.code } })}>{option.label}</button>)}</div></fieldset>)}{form.commentAllowed ? <label className="grid gap-2 border-t border-slate-200 pt-5 text-sm font-bold text-slate-700">Comentários adicionais{form.commentNotice ? <small className="font-normal text-slate-500">{form.commentNotice}</small> : null}<textarea className="min-h-28 rounded-lg border border-slate-300 p-3 font-normal" value={respostas.comentario} onChange={(e) => onChange({ ...respostas, comentario: e.target.value })} /></label> : null}</div><Actions><Button variant="secondary" disabled={isSubmitting} onClick={onBack}>Voltar</Button><Button disabled={!complete || isSubmitting} onClick={onNext}>{isSubmitting ? 'Enviando...' : isLast ? 'Finalizar Pesquisa' : 'Próxima Disciplina'}</Button></Actions>{!complete ? <p className="mt-4 text-center text-sm text-slate-500">Responda todas as questões para continuar.</p> : null}</section>
}
